---
- name: crio | Set latest version
  when: crio_version == 'latest'
  block:
  - name: crio | Get latest version
    ansible.builtin.uri:
      url: https://api.github.com/repos/cri-o/cri-o/releases
      return_content: yes
    register: crio_latest_release_response
  - name: crio | Set latest version variable
    set_fact:
      crio_version: "{{ '.'.join(crio_latest_release_response.json[0].tag_name[1:].split('.')[0:2]) }}"
  - name: crio | Display version
    ansible.builtin.debug:
      msg: "Discovered CRIO version: {{ crio_version }}"
      verbosity: 1

- name: crio | Configure repositories
  ansible.builtin.copy:
    dest: "{{ item.path }}"
    content: "{{ item.content }}"
    mode: '0644'
    owner: root
  loop: "{{ crio_repositories_yum }}"

- name: crio | Install CRI-O
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
    - cri-o
    - container-selinux
