---
- name: Preparations | Load kernel modules on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Preparations | Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - overlay
  - br_netfilter

- name: Preparations | Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: yes
  loop:
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1

- name: Preparations | Install generic packages
  ansible.builtin.apt:
    name:
    - python3-pip
    state: present

- name: Preparations | Install PIP modules
  ansible.builtin.pip:
    name: kubernetes
    state: present
