---
- name: Nginx | Create namespace
  kubernetes.core.k8s:
    name: ingress-nginx
    api_version: v1
    kind: Namespace
    state: present

- name: Nginx | Create ArgoCD object
  kubernetes.core.k8s:
    namespace: argocd
    resource_definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: ingress-nginx
      spec:
        project: default
        source:
          chart: ingress-nginx
          repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.4.2
          helm:
            releaseName: ingress-nginx
        destination:
          server: "https://kubernetes.default.svc"
          namespace: ingress-nginx
        syncPolicy:
          automated:
            selfHeal: true
          syncOptions:
          - CreateNamespace=true
