---
version: 3
images:
  base_image:
    name: ghcr.io/ansible/awx-ee:23.5.0

dependencies:
  galaxy: requirements.yaml
  python: requirements.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
